# test: &default

#   # Credentials for REST APIs
#   client_id: EBWKjlELKMYqRNQ6sYvFo64FtaRLRR5BdHEESmha49TM
#   client_secret: EO422dn3gQLgDbuwqTjzrFgFtaRLRR5BdHEESmha49TM

#   # Mode can be 'live' or 'sandbox'
#   mode: sandbox

#   # Credentials for Classic APIs
#   app_id: APP-80W284485P519543T
#   username: jb-us-seller_api1.paypal.com
#   password: WX4WTU3S8MY44S7F
#   signature: AFcWxV21C7fd0v3bYYYRCpSSRl31A7yDhhsPUU2XhtMoZXsWHFxu-RWy
#   # # With Certificate
#   # cert_path: "config/cert_key.pem"
#   sandbox_email_address: Platform.sdk.seller@gmail.com

#   # # IP Address
#   # ip_address: 127.0.0.1
#   # # HTTP Proxy
#   # http_proxy: http://proxy-ipaddress:3129/

#   # verbose_logging: true

# development:
#   <<: *default

# production:
#   <<: *default
#   mode: live
development: &default
  mode: sandbox
  client_id: EBWKjlELKMYqRNQ6sYvFo64FtaRLRR5BdHEESmha49TM
  client_secret: EO422dn3gQLgDbuwqTjzrFgFtaRLRR5BdHEESmha49TM
  # # with Proxy
  # http_proxy: http://proxy-ipaddress:3129/
  # # with CA File
  # ssl_options:
  #   ca_file: config/cacert.pem
  # # Override Endpoint
  # rest_endpoint: https://api.sandbox.paypal.com
test:
  <<: *default
production:
  mode: live
  client_id: AT_PvRBeZRemQXrhC5UtzQhIuxS2tL2jqvAD5bd9R4Pk36UHyVCSjqgvysYv
  client_secret: ELsS5BBUl9_gf6-JyXfulMoKfUow8NuNQZotpMJIpDqv0DS_uxsIm8rqOc6s